### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by wicksome** [wicksome/wicksome.github.io#1]
- [ ] search
- [ ] thumbnail - show count of comments
- [ ] default thumbnail in archive
- [x] flow chart
- [x] sequence diagram
- [ ] top button
- [ ] social collection
- [ ] presentation page - `reveal.js`
- [ ] category

**markdown-it**
- [ ] emoji
- [ ] markdown-it-mark
- [ ] markdown-it-emoji
- [ ] markdown-it-container
